## Importing the Packages

In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress = True, linewidth = 100, precision = 2)

## Importing the Data

In [6]:
data=np.genfromtxt("Ex2_Exercise-Loan-Data.csv",delimiter = ";",skip_header=1,autostrip=True)
data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

## Checking for Incomplete Data

In [9]:
np.isnan(data).sum()

np.int64(88005)

In [11]:
temp_fill=np.nanmax(data)+1
temp_mean=np.nanmean(data,axis=0)

C:\Users\ZelenePC\AppData\Local\Temp\ipykernel_11072\1935056534.py:2: RuntimeWarning: Mean of empty slice
  temp_mean=np.nanmean(data,axis=0)


In [13]:
temp_stats=np.array([np.nanmin(data,axis=0),
                     temp_mean,
                     np.nanmax(data,axis=0)])

C:\Users\ZelenePC\AppData\Local\Temp\ipykernel_11072\2269169888.py:1: RuntimeWarning: All-NaN slice encountered
  temp_stats=np.array([np.nanmin(data,axis=0),
C:\Users\ZelenePC\AppData\Local\Temp\ipykernel_11072\2269169888.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(data,axis=0)])


In [15]:
temp_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

## Splitting the Dataset

### Splitting the Columns

In [19]:
col_str = np.argwhere(np.isnan(temp_mean)).squeeze()
col_str

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [1909]:
col_num = np.argwhere(np.isnan(temp_mean)==False).squeeze()
col_num

array([ 0,  2,  4,  6,  7, 13])

### Re-importing the Dataset

In [1912]:
data_str = np.genfromtxt("exercise-loan-data.csv",
                            delimiter = ";",
                            skip_header=1,
                            autostrip=True,
                            usecols=col_str,
                           dtype = str)
data_str

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [1913]:
data_num = np.genfromtxt("exercise-loan-data.csv",
                            delimiter = ";",
                            skip_header=1,
                            autostrip=True,
                            usecols=col_num,
                           filling_values = temp_fill)
data_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

### The Names of the Columns

In [1917]:
header_in = np.genfromtxt("exercise-loan-data.csv",
                            delimiter = ";",
                            skip_footer=data.shape[0],
                            autostrip=True,
                           dtype = str)
header_in

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [1918]:
header_str,header_num = header_in[col_str],header_in[col_num]

In [1921]:
header_str

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [1923]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

## Creating Checkpoints:

In [1926]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [1928]:
checkpoint_test = checkpoint("checkpoint-test", header_str, data_str)

In [1930]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [1932]:
np.array_equal(checkpoint_test['data'], data_str)

True

## Manipulating String Columns

In [1935]:
header_str

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [1937]:
header_str[0]="issue_date"

In [1939]:
header_str

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

### Issue Date

In [1941]:
np.unique(data_str[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [1942]:
data_str[:,0]=np.char.strip(data_str[:,0],"-15")
np.unique(data_str[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [1946]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [1948]:
for i in range(13):
        data_str[:,0] = np.where(data_str[:,0] == months[i],
                                          str(i),
                                          data_str[:,0])

In [1950]:
np.unique(data_str[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Loan Status

In [1953]:
header_str

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [1955]:
np.unique(data_str[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [1956]:
np.unique(data_str[:,1]).size

9

In [1959]:
status_bad=(["","Charged Off","Default","Late (31-120 days)"])

In [1961]:
data_str[:,1]=np.where(np.isin(data_str[:,1],status_bad),0,1)
np.unique(data_str[:,1])

array(['0', '1'], dtype='<U69')

### Term

In [1964]:
header_str

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [1966]:
np.unique(data_str[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [1968]:
data_str[:,2]=np.char.strip(data_str[:,2]," months")
np.unique(data_str[:,2])

array(['', '36', '60'], dtype='<U69')

In [1970]:
header_str[2]="term_months"

In [1972]:
header_str

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [1974]:
data_str[:,2]=np.where(data_str[:,2]== "",
                          "60",
                          data_str[:,2])

In [1976]:
np.unique(data_str[:,2])

array(['36', '60'], dtype='<U69')

### Grade and Subgrade

In [1979]:
np.unique(data_str[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [1981]:
np.unique(data_str[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

#### Filling Sub Grade

In [1984]:
for i in np.unique(data_str[:,3])[1:]:
    data_str[:,4] = np.where((data_str[:,4] == '') & (data_str[:,3] == i),
                                      i + '5',
                                      data_str[:,4])

In [1986]:
np.unique(data_str[:,4],return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5]))

In [1988]:
data_str[:,4] = np.where(data_str[:,4]=="",
                            "H1",
                            data_str[:,4])

In [1990]:
np.unique(data_str[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

#### Removing Grade

In [1993]:
data_str=np.delete(data_str,3,axis=1)

In [1995]:
data_str[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [1997]:
header_str=np.delete(header_str,3)

In [1999]:
header_str[3]

np.str_('sub_grade')

#### Converting Sub Grade

In [2002]:
np.unique(data_str[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [2004]:
keys = list(np.unique(data_str[:,3]))                         
values = list(range(1, np.unique(data_str[:,3]).shape[0] + 1)) 
dict_sub_grade = dict(zip(keys, values),dtype=str)

In [2005]:
dict_sub_grade

{np.str_('A1'): 1,
 np.str_('A2'): 2,
 np.str_('A3'): 3,
 np.str_('A4'): 4,
 np.str_('A5'): 5,
 np.str_('B1'): 6,
 np.str_('B2'): 7,
 np.str_('B3'): 8,
 np.str_('B4'): 9,
 np.str_('B5'): 10,
 np.str_('C1'): 11,
 np.str_('C2'): 12,
 np.str_('C3'): 13,
 np.str_('C4'): 14,
 np.str_('C5'): 15,
 np.str_('D1'): 16,
 np.str_('D2'): 17,
 np.str_('D3'): 18,
 np.str_('D4'): 19,
 np.str_('D5'): 20,
 np.str_('E1'): 21,
 np.str_('E2'): 22,
 np.str_('E3'): 23,
 np.str_('E4'): 24,
 np.str_('E5'): 25,
 np.str_('F1'): 26,
 np.str_('F2'): 27,
 np.str_('F3'): 28,
 np.str_('F4'): 29,
 np.str_('F5'): 30,
 np.str_('G1'): 31,
 np.str_('G2'): 32,
 np.str_('G3'): 33,
 np.str_('G4'): 34,
 np.str_('G5'): 35,
 np.str_('H1'): 36,
 'dtype': str}

In [2006]:
for i in np.unique(data_str[:,3]):
        data_str[:,3] = np.where(data_str[:,3] == i, 
                                          str(dict_sub_grade[i]),
                                          data_str[:,3])

In [2007]:
np.unique(data_str[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Verification Status

In [2009]:
np.unique(data_str[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [2010]:
data_str[:,4]=np.where((data_str[:,4]=="") | (data_str[:,4]=="Not Verified"),"0","1")

In [2015]:
np.unique(data_str[:,4])

array(['0', '1'], dtype='<U69')

### URL

In [2020]:
data_str[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [2022]:
data_str[:,5] = np.char.strip(data_str[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [2024]:
data_str[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [2026]:
np.array_equal(data_str[:,5].astype(dtype=np.int32),data[:,0].astype(dtype=np.int32))

True

In [2028]:
data_str=np.delete(data_str,5,axis=1)

In [2030]:
header_str=np.delete(header_str,5)

In [2032]:
np.unique(data_str[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [2034]:
header_str[5]

np.str_('addr_state')

In [2036]:
data_num[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [2038]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

### State Address

In [2041]:
header_str

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [2043]:
header_str[5]="state_address"

In [2045]:
data_str[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [2047]:
np.unique(data_str[:,5]).size

50

In [2049]:
state_names, state_count = np.unique(data_str[:,5], return_counts=True)
state_count_sorted=np.argsort(-state_count)
state_names[state_count_sorted], state_count[state_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'TN', 'CT', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DC', 'DE', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10]))

In [2051]:
data_str[:,5]=np.where(data_str[:,5]=="",str(0),data_str[:,5])

In [2053]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf

In [2056]:
data_str[:,5]=np.where(np.isin(data_str[:,5],states_west),str(1),data_str[:,5])
data_str[:,5]=np.where(np.isin(data_str[:,5],states_south),str(2),data_str[:,5])
data_str[:,5]=np.where(np.isin(data_str[:,5],states_midwest),str(3),data_str[:,5])
data_str[:,5]=np.where(np.isin(data_str[:,5],states_east),str(4),data_str[:,5])

In [2058]:
np.unique(data_str[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

## Converting to Numbers

In [2061]:
data_str

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [2063]:
data_str.astype(int)

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [2065]:
data_str=data_str.astype(int)

In [2067]:
np.isnan(data_str).sum()

np.int64(0)

### Checkpoint 1: Strings

In [2070]:
checkpoint_strings = checkpoint("Checkpoint_Strings",header_str,data_str)

In [2072]:
checkpoint_strings["header"]

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [2074]:
checkpoint_strings["data"]

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [2076]:
np.array_equal(checkpoint_strings["data"],data_str)

True

## Manipulating Numeric Columns

In [2079]:
data_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [2081]:
np.isnan(data_num).sum()

np.int64(0)

### Substitute "Filler" Values

In [2084]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### ID

In [2087]:
np.isin(header_num[0],temp_fill).sum()

np.int64(0)

#### Temporary Stats

In [2090]:
temp_stats[:,col_num]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

#### Funded Amount

In [2093]:
data_num[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [2095]:
data_num[:,2] = np.where(data_num[:,2] == temp_fill, 
                                  temp_stats[0, col_num[2]],
                                  data_num[:,2])
data_num[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [2097]:
temp_stats[0,col_num[3]]

np.float64(6.0)

#### Loaned Amount, Interest Rate, Total Payment, Installment

In [2100]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [2102]:
for i in [1,3,4,5]:
    data_num[:,i] = np.where(data_num[:,i] == temp_fill, 
                                  temp_stats[2, col_num[i]],
                                  data_num[:,i])

In [2104]:
data_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

### Currency Change

#### The Exchange Rate

In [2108]:
EUR_USD=np.genfromtxt("exercise_EUR_USD.csv",delimiter=",",autostrip=True,skip_header=True,usecols=3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [2110]:
np.unique(data_str[:,0])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [2112]:
exchange_rate=data_str[:,0]

for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                             EUR_USD[i-1],
                             exchange_rate)    

exchange_rate = np.where(exchange_rate == 0,
                         np.mean(EUR_USD),
                         exchange_rate)    

exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [2114]:
exchange_rate.shape

(10000,)

In [2116]:
data_num.shape

(10000, 6)

In [2118]:
exchange_rate=np.reshape(exchange_rate,(10000,1))

In [2120]:
data_num=np.hstack((data_num,exchange_rate))

In [2122]:
header_num=np.concatenate((header_num,np.array(["exchange_rate"])))
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

#### From USD to EUR

In [2125]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [2127]:
dollar_cols = np.array([1,2,4,5])

In [2129]:
data_num[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [2131]:
for i in dollar_cols:
    data_num = np.hstack((data_num, np.reshape(data_num[:,i] / data_num[:,6], (10000,1))))

In [2133]:
data_num.shape

(10000, 11)

In [2135]:
data_num

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

#### Expanding the header

In [2138]:
header_add = np.array([column_name + '_EUR' for column_name in header_num[dollar_cols]])

In [2140]:
header_add

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [2142]:
header_num=np.concatenate((header_num, header_add))

In [2144]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [2146]:
header_num[dollar_cols] = np.array([column_name + '_USD' for column_name in header_num[dollar_cols]])

In [2148]:
header_num

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [2150]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [2152]:
header_num=header_num[columns_index_order]

In [2154]:
data_num=data_num[:,columns_index_order]

In [2156]:
data_num

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

### Interest Rate

In [2159]:
header_num

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [2161]:
data_num[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [2163]:
data_num[:,5]=data_num[:,5]/100

In [2165]:
data_num[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

### Checkpoint 2: Numeric

In [2168]:
checkpoint_num = checkpoint("Checkpoint_Numeric",header_num,data_num)

In [2170]:
checkpoint_num['header'], checkpoint_num['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

## Creating the "Complete" Dataset

In [2173]:
checkpoint_strings["data"].shape

(10000, 6)

In [2175]:
checkpoint_num["data"].shape

(10000, 11)

In [2177]:
loan_data=np.hstack((checkpoint_num["data"],checkpoint_strings["data"]))

In [2179]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [2181]:
np.isnan(loan_data).sum()

np.int64(0)

In [2183]:
header_full=np.concatenate((checkpoint_num["header"],checkpoint_strings["header"]))

## Sorting the New Dataset

In [2188]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [2192]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [2196]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999])

## Storing the New Dataset

In [2206]:
loan_data = np.vstack((header_full,loan_data))

In [2210]:
np.savetxt("Ex2_Loan_Data_prepro.csv",loan_data,fmt = "%s", delimiter=",")